version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: lesson4-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Lesson4
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # скрипты для авто-инициализации

volumes:
  pgdata:
